version: '3.7'

services:
  app:
    container_name: server
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: [ "/home/app/docker/backend/server-entrypoint.sh" ]
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    expose:
      - 8000
    env_file:
      - ./stage_projet/stage_projet/.env  

  nginx:
    container_name: nginx
    build: ./docker/nginx
    restart: always
    volumes:
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media
    ports:
      - 4001:80 
    depends_on:
      - app
    logging:
      options:
        max-size: 10m

  redis:
    container_name: redis
    restart: always
    image: redis:7.0.5-alpine
    expose:
      - 6379

  deamons:
    container_name: celery-beat-deamons
    restart: always
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    entrypoint: [ "/home/app/docker/backend/daemon-entrypoint.sh" ]
    env_file:
      - ./stage_projet/stage_projet/.env
    depends_on:
      - app
      - redis
    volumes:
      - ./docker/supervisor/celery.conf:/etc/supervisor/conf.d/celery.conf
      - static_volume:/home/app/backend/static
      - media_volume:/home/app/backend/media

  #db:
   # container_name: postgres
   # image: postgres:latest
    #restart: always
    #environment:
      #POSTGRES_USER: postgres
     # POSTGRES_PASSWORD: stage
      #POSTGRES_DB: projet_stage
    #ports:
     # - "5432:5432"
    #volumes:
      #- pg_data:/var/lib/postgresql/data

volumes:
  static_volume: {}
  media_volume: {}
  pg_data: {}
