# Generated by Django 4.2.13 on 2024-06-23 21:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('HH', 'Hiphop'), ('RNB', 'Rnb'), ('DJZ', 'Soul')], max_length=10)),
                ('year_formed', models.IntegerField(validators=[django.core.validators.MinValueValidator(2021), django.core.validators.MaxValueValidator(2024)])),
                ('biography', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('off_homepage', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
