# Generated by Django 4.2.13 on 2025-01-11 02:31

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='resultat',
            field=models.ImageField(default='image.jpg', upload_to=listings.models.get_upload_to),
            preserve_default=False,
        ),
    ]
