# Generated by Django 4.2.13 on 2024-08-02 08:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='linked_infirmiers',
            field=models.ManyToManyField(blank=True, related_name='linked_medecins', to=settings.AUTH_USER_MODEL),
        ),
    ]
