# Generated by Django 4.2.13 on 2024-07-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='diagnostique_retenu',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
