# Generated by Django 4.2.13 on 2024-07-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='causedudeces',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='commentaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datedeces',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datederniererelance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datedernierevisite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datedetransfert',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='daterefus',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='decesliea',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='lieudeces',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='nouveaucentredesuivi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='numerodedossierdanslecentredetransfert',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='raison',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='remplipar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='typedenouvelle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='typederelance',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
