# Generated by Django 4.2.13 on 2024-07-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='avp',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='operachir',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
    ]
