# Generated by Django 4.2.13 on 2024-07-29 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numeropatient',
            field=models.PositiveIntegerField(max_length=100, unique=True),
        ),
    ]
