# Generated by Django 4.2.13 on 2024-10-13 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan_biologique',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='bilan_imagerie',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='hospita',
        ),
        migrations.RemoveField(
            model_name='ordonnance',
            name='consulation',
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilan_imagerie',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.patient'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listings.patient'),
            preserve_default=False,
        ),
    ]
