# Generated by Django 4.2.13 on 2024-07-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_categorie_chu_consultation_lit_medicament_ordonnance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constante',
            name='imc',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constante',
            name='pouls',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constante',
            name='tad',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constante',
            name='tas',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
