# Generated by Django 4.2.13 on 2024-10-24 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_customuser_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='nom',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
