# Generated by Django 4.2.13 on 2024-07-22 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_antecedant_chirurgical_avp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='cesarienne',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='prisecontraceptif',
            field=models.CharField(choices=[('oui', 'oui'), ('n', 'non')], max_length=3),
        ),
    ]
