# Generated by Django 4.2.13 on 2024-07-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_sortie_causedudeces_alter_sortie_commentaire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan_biologique',
            name='prix',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
