# Generated by Django 4.2.13 on 2024-08-23 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_patientlit_dateoccupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='numerodelit',
        ),
    ]
