# Generated by Django 4.2.13 on 2024-07-04 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_categorie_chu_consultation_lit_medicament_ordonnance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicament',
            old_name='date',
            new_name='dateprescription',
        ),
        migrations.RemoveField(
            model_name='bilan_biologique',
            name='date',
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='se_trouver',
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='datereceptionechantillon',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='dateremiseresultat',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='marqueurVir',
            field=models.CharField(choices=[('Sérologie rétroviral', 'Sérologie rétroviral'), ('IgG anti VHE ', 'IgG anti VHE '), ('IgM anti VHE ', 'IgM anti VHE '), ('Ac anti VHD ', 'Ac anti VHD '), ('Ac anti HBe ', 'Ac anti HBe '), ('Ag HBe ', 'Ag HBe ')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='resultat',
            field=models.CharField(choices=[('positif', 'positif'), ('négatif ', 'négatif ')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='unite',
            field=models.CharField(choices=[('UI/ ml  ', 'UI/ ml'), ('mmol/ l', 'mmol/ l'), ('g/l  ', 'g/l'), ('/mm3', '/mm3')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lit',
            name='categorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='listings.categorie'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='motifsortie',
            field=models.CharField(choices=[('déces', 'déces'), ('fuite', 'fuite'), ('guérit', 'guérit')], default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='prochaineconsultation',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='echographie_ou_radiograpgie',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='renseignementclinique',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='debut_signe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='histoiredemaladie',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='medoc_en_cours',
            field=models.CharField(blank=True, max_length=253, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motifdeconsultation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='nombredeverre_alcool',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='nombrepaquettabac',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescripteur_consultation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prise_therap_tarditionnelle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='renseignementclinic',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='resultat',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='signe_asso_gene',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='signe_digestifs',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='signe_extra_digestif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='numerofact',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(choices=[('300 mg/j', '300 mg/j'), ('25 mg/j', '25 mg/j'), ('0.5 mg/j', '0.5 mg/j'), ('100 mg/j', '100 mg/j'), ('600 mg/j', '600 mg/j'), ('180 mg/semaine', '180 mg/semaine')], max_length=100),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nommedicament',
            field=models.CharField(choices=[('TDF', 'TDF'), ('TAF', 'TAF'), ('Entecavir', 'Entecavir'), ('Lamivudine', 'Lamivudine'), ('Adéfovir', ' Adéfovir'), ('Telbivudine', 'Telbivudine'), ('Interferon pegylé', 'Interferon pegylé'), ('Interféron pégylé', 'Interféron pégylé')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ordonnancemedicament',
            name='quantite',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datesortie',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='categorielit',
        ),
    ]
