# Generated by Django 4.2.13 on 2024-08-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_customuser_linked_infirmiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='linked_infirmiers',
        ),
    ]
