# Generated by Django 4.2.13 on 2025-01-11 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_bilan_imagerie_resultat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='echographie',
            field=models.TextField(default='vd'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='radiographie',
            field=models.TextField(default='ds'),
            preserve_default=False,
        ),
    ]
