# Generated by Django 4.2.13 on 2024-07-30 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_consultation_diagnostique_retenu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonnance',
            old_name='Consulation',
            new_name='consulation',
        ),
        migrations.RenameField(
            model_name='ordonnancemedicament',
            old_name='Medicament',
            new_name='medicament',
        ),
    ]
