# Generated by Django 4.2.13 on 2024-07-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_patient_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='mdp',
        ),
    ]
