# Generated by Django 4.2.13 on 2025-01-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_bilan_imagerie_echographie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='echographie',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='radiographie',
            field=models.TextField(blank=True, null=True),
        ),
    ]
