# Generated by Django 4.2.13 on 2024-07-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_constante_imc_constante_pouls_constante_tad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='caution_versee',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='facture',
            name='cout_sejour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_versement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='duree_sejour',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='modepaiment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='remboursement',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='rest_a_payer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
