# Generated by Django 4.2.13 on 2024-07-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_consulation_ordonnance_consulation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_biologique',
            name='resultatmodalite',
            field=models.CharField(choices=[('positif', 'positif'), ('négatif', 'négatif')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bilan_biologique',
            name='typeexamen',
            field=models.CharField(choices=[('Sérologie rétroviral', 'Sérologie rétroviral'), ('IgG anti VHE', 'IgG anti VHE'), ('IgM anti VHE', 'IgM anti VHE'), ('Ac anti VHD', 'Ac anti VHD'), ('Ac anti HBe', 'Ac anti HBe'), ('Ag HBe', 'Ag HBe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bilan_biologique',
            name='unite',
            field=models.CharField(choices=[('UI/ ml', 'UI/ ml'), ('mmol/ l', 'mmol/ l'), ('g/l', 'g/l'), ('/mm3', '/mm3')], max_length=100),
        ),
    ]
