# Generated by Django 4.2.13 on 2024-07-19 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_customuser_mdp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Personnel_soignant',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='Personnel_soignant',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='sortie',
            old_name='Personnel_soignant',
            new_name='user',
        ),
    ]
