# Generated by Django 4.2.13 on 2024-07-22 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_antecedant_genecologique_cesarienne_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_medical',
            name='accidexposang',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='cirrhose',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='diabete',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dyslipidemie',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hepatiteviraleb',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hepatiteviralec',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hepatiteviraled',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hta',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='ictere',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='partageobjettoilette',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='rapportsexuelnonprotege',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='toxicomanie',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='transfusion_sanguine',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='transplanhepatique',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='vaccination_vha',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='vaccination_vhb',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
    ]
