# Generated by Django 4.2.13 on 2024-07-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_antecedant_chirurgical_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='numeropatient',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
