# Generated by Django 4.2.13 on 2024-07-16 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_bilan_biologique_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan_biologique',
            name='datereceptionechantillon',
        ),
        migrations.RemoveField(
            model_name='bilan_biologique',
            name='dateremiseresultat',
        ),
    ]
