# Generated by Django 4.2.13 on 2024-07-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_date_medicament_dateprescription_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel_soignant',
            name='date',
        ),
    ]
