# Generated by Django 4.2.13 on 2024-08-02 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_customuser_linked_infirmiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
    ]
