# Generated by Django 4.2.13 on 2024-10-24 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_customuser_nom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bilan_biologique',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-24'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordonnance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default='2024-10-24'),
            preserve_default=False,
        ),
    ]
