# Generated by Django 4.2.13 on 2024-07-14 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_facture_caution_versee_facture_cout_sejour_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sortie',
            name='patient',
        ),
        migrations.AddField(
            model_name='sortie',
            name='personnel_soignant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='listings.personnel_soignant'),
            preserve_default=False,
        ),
    ]
