# Generated by Django 4.2.13 on 2024-11-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_bilan_biologique_date_ordonnance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='contact1',
            field=models.CharField(default='0788932734', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='contact2',
            field=models.CharField(default='0788131504', max_length=20),
            preserve_default=False,
        ),
    ]
