# Generated by Django 4.2.13 on 2024-07-19 01:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_rename_personnel_soignant_user_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Personnel_soignant',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='user',
        ),
        migrations.AddField(
            model_name='consultation',
            name='CustomUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='CustomUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
