# Generated by Django 4.2.13 on 2024-07-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_remove_bilan_biologique_datereceptionechantillon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
