# Generated by Django 4.2.13 on 2024-07-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_antecedant_medical_accidexposang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='Bilanbiologiqueant',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='', max_length=10),
            preserve_default=False,
        ),
    ]
