# Generated by Django 4.2.13 on 2024-08-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_customuser_disponible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='avp',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='dateavp',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_chirurgical',
            name='operachir',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cirrhose_ASC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cirrhose_COL',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cirrhose_DSC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cpf_ASC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cpf_COL',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cpf_DSC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hepatie_vir_ASC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hepatie_vir_COL',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hepatie_vir_DSC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='cesarienne',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='datecesarienne',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='datederniereregle',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='gestite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='parite',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_genecologique',
            name='prisecontraceptif',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='accidexposang',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='cirrhose',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvirb',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvirc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datehepvird',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='datransing',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='diabete',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevha',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dosevhb',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='dyslipidemie',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hepatiteviraleb',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hepatiteviralec',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hepatiteviraled',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='hta',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='ictere',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='partageobjettoilette',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='precisionautre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='rapportsexuelnonprotege',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='toxicomanie',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='transfusion_sanguine',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='transplanhepatique',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='vaccination_vha',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_medical',
            name='vaccination_vhb',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numeropatient',
            field=models.CharField(max_length=100),
        ),
    ]
