# Generated by Django 4.2.13 on 2024-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_bilan_biologique_resultatmodalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='echographie_ou_radiograpgie',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
