# Generated by Django 4.2.13 on 2024-10-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_patient_commune_alter_patient_nationalite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalisationlit',
            name='origine',
            field=models.CharField(max_length=27),
        ),
    ]
