# Generated by Django 4.2.13 on 2024-10-15 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_hospitalisationlit_origine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='email',
            field=models.EmailField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='patient',
            name='numeropatient',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='patient',
            name='personne_a_contacter',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(blank=True, choices=[('féminin', 'féminin'), ('masculin', 'masculin')], max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ville',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
