# Generated by Django 4.2.13 on 2024-07-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_bilan_imagerie_echographie_ou_radiograpgie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='date_versement',
            field=models.DateField(blank=True, null=True),
        ),
    ]
