# Generated by Django 4.2.13 on 2024-07-15 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_remove_sortie_patient_sortie_personnel_soignant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sortie',
            old_name='prochaineconsultation',
            new_name='datedeces',
        ),
        migrations.AddField(
            model_name='sortie',
            name='causedudeces',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='commentaire',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='datederniererelance',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='datedernierevisite',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='datedetransfert',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='daterefus',
            field=models.DateField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='decesliea',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='lieudeces',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='nouveaucentredesuivi',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='numerodedossierdanslecentredetransfert',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='raison',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='remplipar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='typedenouvelle',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='typederelance',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sortie',
            name='motifsortie',
            field=models.CharField(max_length=50),
        ),
    ]
