# Generated by Django 4.2.13 on 2025-01-09 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_patient_contact1_alter_patient_contact2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact',
            field=models.CharField(default='0788932734', max_length=20),
            preserve_default=False,
        ),
    ]
