# Generated by Django 4.2.13 on 2024-07-19 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_user_personnel_soignant_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Lit',
            new_name='lit',
        ),
    ]
