# Generated by Django 4.2.13 on 2024-07-23 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_consultation_bilanbiologiqueant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='band',
        ),
        migrations.DeleteModel(
            name='band',
        ),
        migrations.DeleteModel(
            name='listing',
        ),
    ]
