# Generated by Django 4.2.13 on 2024-07-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_rename_lit_patient_lit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lit',
            old_name='Categorie',
            new_name='categorie',
        ),
    ]
