# Generated by Django 4.2.13 on 2024-07-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_remove_listing_band_delete_band_delete_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='datesortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
