# Generated by Django 4.2.13 on 2024-07-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_facture_date_versement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='montantpaye',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
