# Generated by Django 4.2.13 on 2024-07-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_facture_montantpaye'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='cout_sejour',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='modepaiment',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='montantpaye',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='remboursement',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='facture',
            name='rest_a_payer',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
