# Generated by Django 4.2.13 on 2024-10-17 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_examen_physique_diurese_examen_physique_eva_douleur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examen_physique',
            name='diurese',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examen_physique',
            name='eva_douleur',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examen_physique',
            name='frequence_cardiaque',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examen_physique',
            name='frequence_respiratoire',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examen_physique',
            name='nombre_de_selles',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examen_physique',
            name='nombre_de_vomissements',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='examen_physique',
            name='saturation_doxygene',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
