# Generated by Django 4.2.13 on 2024-07-19 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_rename_categorie_lit_categorie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='CustomUser',
            new_name='customUser',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='diagnostique',
            old_name='Consultation',
            new_name='consultation',
        ),
    ]
