# Generated by Django 4.2.13 on 2024-07-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='refpersoignant',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, default='', primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
