# Generated by Django 4.2.13 on 2024-09-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_antecedant_chirurgical_autre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='decesliea',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='lieudeces',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='motifsortie',
            field=models.CharField(max_length=21),
        ),
    ]
