# Generated by Django 4.2.13 on 2024-07-23 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_sortie_datesortie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='patient',
            field=models.ForeignKey(default='2', on_delete=django.db.models.deletion.CASCADE, to='listings.patient'),
            preserve_default=False,
        ),
    ]
