# Generated by Django 4.2.13 on 2024-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_remove_customuser_refpersoignant_customuser_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='id',
        ),
        migrations.AddField(
            model_name='customuser',
            name='refpersoignant',
            field=models.AutoField(default='', primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
