# Generated by Django 4.2.13 on 2024-10-18 13:16

from django.db import migrations, models
import listings.models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_examen_physique_diurese_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilan_imagerie',
            name='resultat',
            field=models.ImageField(blank=True, null=True, upload_to=listings.models.get_upload_to),
        ),
    ]
