# Generated by Django 4.2.13 on 2024-09-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_alter_sortie_decesliea_alter_sortie_lieudeces_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='medoc_en_cours',
            field=models.TextField(blank=True, null=True),
        ),
    ]
