# Generated by Django 4.2.13 on 2024-09-04 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_consultation_medoc_en_cours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='renseignementclinic',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='resultat',
        ),
    ]
