# Generated by Django 4.2.13 on 2024-07-19 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_rename_patient_antecedant_chirurgical_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedant_chirurgical',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='antecedant_familial',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='antecedant_genecologique',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='antecedant_medical',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='bilan_biologique',
            old_name='consultation',
            new_name='Consultation',
        ),
        migrations.RenameField(
            model_name='bilan_imagerie',
            old_name='consultation',
            new_name='Consultation',
        ),
        migrations.RenameField(
            model_name='constante',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='service',
            new_name='Service',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='type_personnel_soignant',
            new_name='Type_personnel_soignant',
        ),
        migrations.RenameField(
            model_name='diagnostique',
            old_name='consultation',
            new_name='Consultation',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='patient',
            new_name='Patient',
        ),
        migrations.RenameField(
            model_name='hospitalisation',
            old_name='consultation',
            new_name='Consultation',
        ),
        migrations.RenameField(
            model_name='lit',
            old_name='categorie',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lit',
            new_name='Lit',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='customUser',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='customUser',
        ),
        migrations.AddField(
            model_name='consultation',
            name='Personnel_soignant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='listings.personnel_soignant'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='Personnel_soignant',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='listings.personnel_soignant'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='service',
            field=models.CharField(choices=[('gastro-entérologie', 'Gastro Enterologie'), ('chirurgie', 'Chirurgie')], max_length=100),
        ),
    ]
