# Generated by Django 4.2.13 on 2024-08-01 09:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chu',
            name='datecreation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_versement',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datederniererelance',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datedernierevisite',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datedetransfert',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='daterefus',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='datesortie',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='lieudeces',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='motifsortie',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='sortie',
            name='remplipar',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
