# Generated by Django 4.2.13 on 2024-07-24 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_constante_imc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='date_naissance',
            field=models.DateField(blank=True, null=True),
        ),
    ]
