# Generated by Django 4.2.13 on 2024-10-20 16:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_alter_bilan_imagerie_resultat'),
    ]

    operations = [
        migrations.AddField(
            model_name='sortie',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
