# Generated by Django 4.2.13 on 2024-07-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_patient_antecedant_chirurgical_patient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedant_chirurgical',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='antecedant_familial',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='antecedant_genecologique',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='antecedant_medical',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='bilan_biologique',
            old_name='Consultation',
            new_name='consultation',
        ),
        migrations.RenameField(
            model_name='bilan_imagerie',
            old_name='Consultation',
            new_name='consultation',
        ),
        migrations.RenameField(
            model_name='constante',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Service',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='Type_personnel_soignant',
            new_name='type_personnel_soignant',
        ),
        migrations.RenameField(
            model_name='diagnostique',
            old_name='Consultation',
            new_name='consultation',
        ),
        migrations.RenameField(
            model_name='facture',
            old_name='Patient',
            new_name='patient',
        ),
        migrations.RenameField(
            model_name='hospitalisation',
            old_name='Consultation',
            new_name='consultation',
        ),
        migrations.RenameField(
            model_name='lit',
            old_name='Categorie',
            new_name='categorie',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Lit',
            new_name='lit',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='Personnel_soignant',
        ),
        migrations.RemoveField(
            model_name='sortie',
            name='Personnel_soignant',
        ),
        migrations.AddField(
            model_name='consultation',
            name='customUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='customUser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hospitalisation',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.service'),
        ),
    ]
