# Generated by Django 4.2.13 on 2024-07-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_patient_date_naissance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='debut_signe',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='motifdeconsultation',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prescripteur_consultation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='diagnostique',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
