# Generated by Django 4.2.13 on 2024-07-15 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_sortie_datesortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='datesortie',
            field=models.DateField(blank=True, null=True),
        ),
    ]
