# Generated by Django 4.2.13 on 2024-08-01 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_chu_datecreation_alter_facture_date_versement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='decesliea',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
