# Generated by Django 4.2.13 on 2024-09-04 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_remove_consultation_renseignementclinic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultation',
            name='histoiredemaladie',
        ),
    ]
