# Generated by Django 4.2.13 on 2024-10-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_sortie_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='customUser',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
