# Generated by Django 4.2.13 on 2024-07-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_consultation_debut_signe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='numeropatient',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
