# Generated by Django 4.2.13 on 2024-08-01 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_sortie_decesliea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='datesortie',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
