# Generated by Django 4.2.13 on 2024-10-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_ordonnance_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='Bilanbiologiqueant',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prise_therap_tarditionnelle',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
    ]
