# Generated by Django 4.2.13 on 2024-07-15 00:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_sortie_datesortie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='datesortie',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
