# Generated by Django 4.2.13 on 2024-10-23 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_consultation_bilanbiologiqueant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisationlit',
            name='lit',
        ),
        migrations.RemoveField(
            model_name='hospitalisationlit',
            name='origine',
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='lit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='listings.lit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='origine',
            field=models.CharField(default='CHU', max_length=27),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hospitalisationlit',
            name='duree',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
