# Generated by Django 4.2.13 on 2024-07-26 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_patient_numeropatient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_familial',
            name='ascite',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=4),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cirrhose_ASC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cirrhose_COL',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cirrhose_DSC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cpf_ASC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cpf_COL',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cpf_DSC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='cvc',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=4),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hepatie_vir_ASC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hepatie_vir_COL',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hepatie_vir_DSC',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='hippocraismdigital',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=4),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='oncleblanc',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
        migrations.AlterField(
            model_name='antecedant_familial',
            name='splenomegalie',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=4),
        ),
    ]
