# Generated by Django 4.2.13 on 2024-09-04 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_consultation_motifdeconsultation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bilan_biologique',
            name='resultatmodalite',
        ),
    ]
