# Generated by Django 4.2.13 on 2024-09-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_remove_bilan_biologique_resultatmodalite'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitalisation',
            name='origine',
            field=models.CharField(blank=True, max_length=28, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profession',
            field=models.CharField(max_length=49),
        ),
    ]
