# Generated by Django 4.2.13 on 2024-07-26 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_antecedant_familial_ascite_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='ascite',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='autre',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='autresignephysique',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='conscience',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='cvc',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='flechehepatique',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='hippocraismdigital',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='oncleblanc',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='splenomegalie',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='statutoms',
        ),
    ]
