# Generated by Django 4.2.13 on 2024-07-15 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_sortie_datesortie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilan_biologique',
            old_name='resultat',
            new_name='resultatmodalite',
        ),
        migrations.RenameField(
            model_name='bilan_biologique',
            old_name='marqueurVir',
            new_name='typeexamen',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='imc',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='poids',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='pouls',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='taille',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='temperature',
        ),
        migrations.RemoveField(
            model_name='antecedant_familial',
            name='tension_art',
        ),
        migrations.AddField(
            model_name='bilan_biologique',
            name='resultatnumerique',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
