# Generated by Django 4.2.13 on 2024-09-05 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_hospitalisation_origine_alter_patient_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sortie',
            name='decesliea',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
