# Generated by Django 4.2.13 on 2024-07-27 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='patient_nom',
        ),
        migrations.AddField(
            model_name='notification',
            name='patient',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='listings.patient'),
            preserve_default=False,
        ),
    ]
