# Generated by Django 4.2.13 on 2024-09-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0017_alter_bilan_imagerie_date_alter_constante_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bilan_imagerie',
            old_name='echographie_ou_radiograpgie',
            new_name='resultat',
        ),
        migrations.RemoveField(
            model_name='bilan_imagerie',
            name='renseignementclinique',
        ),
        migrations.RemoveField(
            model_name='hospitalisation',
            name='service',
        ),
        migrations.AddField(
            model_name='antecedant_medical',
            name='hemorragiedigestive',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='antecedant_medical',
            name='ulceregastroduodenal',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bilan_imagerie',
            name='dateexam',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bilan_imagerie',
            name='typeexam',
            field=models.CharField(default='', max_length=21),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sortie',
            name='nompracticien',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
    ]
