# Generated by Django 4.2.13 on 2024-09-09 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_rename_echographie_ou_radiograpgie_bilan_imagerie_resultat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicament',
            name='dosage',
        ),
        migrations.AddField(
            model_name='antecedant_medical',
            name='epigastralgies',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], default='', max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='constante',
            name='lmc',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='constante',
            name='lxo',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='constante',
            name='resultattoucherectal',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='constante',
            name='shp',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='constante',
            name='sih',
            field=models.CharField(blank=True, choices=[('oui', 'oui'), ('non', 'non')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateacanti_vhc',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateacanti_vhd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateaghbs',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='dateserologie_retrovi',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consultation',
            name='datetransa',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordonnancemedicament',
            name='raison',
            field=models.CharField(default='', max_length=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordonnancemedicament',
            name='taitementhospi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bilan_biologique',
            name='typeexamen',
            field=models.CharField(choices=[('Hémogramme', 'Hémogramme'), ('Blan hépatique', 'Blan hépatique'), ('IgM anti VHE', 'IgM anti VHE'), ('Ac anti VHD', 'Ac anti VHD'), ('Ac anti HBe', 'Ac anti HBe'), ('Ag HBe', 'Ag HBe')], max_length=100),
        ),
        migrations.AlterField(
            model_name='bilan_biologique',
            name='unite',
            field=models.CharField(choices=[('Ul/l', 'Ul/ ml'), ('mmol/ l', 'mmol/ l'), ('g/l', 'g/l'), ('/mm3', '/mm3'), ('%', '%')], max_length=100),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='Bilanbiologiqueant',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='prise_therap_tarditionnelle',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non')], max_length=3),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nommedicament',
            field=models.CharField(choices=[('TDF 300 mg/j', 'TDF 300 mg/j'), ('TAF 25 mg/j', 'TAF 25 mg/j'), ('Entecavir 0.5 mg/j', 'Entecavir 0.5 mg/j'), ('Lamivudine 100 mg/j', 'Lamivudine 100 mg/j'), ('Adéfovir 25 mg/j', 'Adéfovir 25 mg/j'), ('Telbivudine 600 mg/j', 'Telbivudine 600 mg/j'), ('Interferon pegylé 180 g/semaine', 'Interferon pegylé 180 g/semaine'), ('TDF 300 mg + Interféron pégylé  180 g/semaine', 'TDF 300 mg + Interféron pégylé  180 g/semaine'), ('Bulevirtide', 'Bulevirtide'), ('Interferon pégylé  180 g/semaine', 'Interferon pégylé  180 g/semaine'), ('Sofosbuvir + Velpatasvir Cp avec Sofosbuvir 400 mg et Velpatasvir 100 mg 1 cp/j', 'Sofosbuvir + Velpatasvir Cp avec Sofosbuvir 400 mg et Velpatasvir 100 mg 1 cp/j'), ('Sofosbuvir + Ledipasvir Cp  avec Sofosbuvir 400 mg et Ledipasvir 90 mg 1 cp/j', 'Sofosbuvir + Ledipasvir Cp  avec Sofosbuvir 400 mg et Ledipasvir 90 mg 1 cp/j'), ('Sofosbuvir + daclastavir  avec Sofosbuvir Cp à 400 mg et daclastavir 60 mg  1 cp/j', 'Sofosbuvir + daclastavir  avec Sofosbuvir Cp à 400 mg et daclastavir 60 mg  1 cp/j'), ('Sofosbuvir + daclastavir  avec Sofosbuvir Cp à 400 mg et daclastavir 30 mg  1 cp/j ', 'Sofosbuvir + daclastavir  avec Sofosbuvir Cp à 400 mg et daclastavir 30 mg  1 cp/j'), ('Sofosbuvir + daclastavir  avec Sofosbuvir Cp à 400 mg et daclastavir 90 mg  1 cp/j', 'Sofosbuvir + daclastavir  avec Sofosbuvir Cp à 400 mg et daclastavir 90 mg  1 cp/j'), ('Ribavirine Cp à 200 ou 400 mg  1000 mg/j si pds < 75 kg 1200 mg/j si pds ≥ 75 kg', 'Ribavirine Cp à 200 ou 400 mg  1000 mg/j si pds < 75 kg 1200 mg/j si pds ≥ 75 kg'), ('Dasabuvir  Cp à 250 mg 1 comprimé matin et soir', 'Dasabuvir  Cp à 250 mg 1 comprimé matin et soir'), ('Paritaprevir/ritonavir + Ombitasvir Cp avec Paritaprevir 75 mg, ritonavir 50 mg et Ombitasvir 12,5 mg 2 comprimés une fois par jour', 'Paritaprevir/ritonavir + Ombitasvir Cp avec Paritaprevir 75 mg, ritonavir 50 mg et Ombitasvir 12,5 mg 2 comprimés une fois par jour'), ('Vitamine E', 'Vitamine E'), ('EPO', 'EPO'), ('G CSF', 'G CSF'), ('Thrombopoietine', 'Thrombopoietine'), ('Vaccination VHA', 'Vaccination VHA'), ('Vaccination VHB', 'Vaccination VHB'), ('Grazoprevir + Elbasvir Cp avec Grazoprevir 100 mg et Elbasvir 50 mg 1 cp par jour', 'Grazoprevir + Elbasvir Cp avec Grazoprevir 100 mg et Elbasvir 50 mg 1 cp par jour'), ('Glecaprevir + Pibrentasvir Cp avec Glecaprevir 100 mg et Pibrentasvir 40 mg 3 cp une fois par jour', 'Glecaprevir + Pibrentasvir Cp avec Glecaprevir 100 mg et Pibrentasvir 40 mg 3 cp une fois par jour'), ('Sofosbuvir + Velpatasvir + Voxilaprevir Comprimés avec Sofosbuvir 400 mg et Velpatasvir 100 mg et Voxilaprevir 100 mg 1 comprimé par jour', 'Sofosbuvir + Velpatasvir + Voxilaprevir Comprimés avec Sofosbuvir 400 mg et Velpatasvir 100 mg et Voxilaprevir 100 mg 1 comprimé par jour')], max_length=150),
        ),
    ]
