# Generated by Django 4.2.13 on 2024-09-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_remove_medicament_dosage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='antecedant_medical',
            name='diabete',
            field=models.CharField(choices=[('oui', 'oui'), ('non', 'non'), ('ne sait pas', 'ne sait pas')], max_length=11),
        ),
    ]
