# Generated by Django 4.2.13 on 2024-09-16 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_alter_antecedant_medical_diabete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='acanti_vhc',
            field=models.CharField(blank=True, choices=[('positif', 'positif'), ('négatif', 'négatif')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='acanti_vhd',
            field=models.CharField(blank=True, choices=[('positif', 'positif'), ('négatif', 'négatif')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='aghbs',
            field=models.CharField(blank=True, choices=[('positif', 'positif'), ('négatif', 'négatif')], max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='serologie_retrovi',
            field=models.CharField(blank=True, choices=[('positif', 'positif'), ('négatif', 'négatif')], max_length=7, null=True),
        ),
    ]
