# Generated by Django 4.2.13 on 2024-09-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_consultation_acanti_vhc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='transaminase',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
