# Generated by Django 4.2.13 on 2024-09-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0022_alter_consultation_transaminase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospitalisation',
            name='origine',
        ),
        migrations.AddField(
            model_name='hospitalisation',
            name='datehospitalisationsortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
