# Generated by Django 4.2.13 on 2024-09-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_remove_hospitalisation_origine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordonnancemedicament',
            old_name='date',
            new_name='dateajout',
        ),
        migrations.RemoveField(
            model_name='medicament',
            name='dateprescription',
        ),
        migrations.RemoveField(
            model_name='ordonnancemedicament',
            name='taitementhospi',
        ),
        migrations.AddField(
            model_name='medicament',
            name='dateajout',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicament',
            name='dosage',
            field=models.CharField(blank=True, choices=[('300 mg/j', '300 mg/j'), ('25 mg/j', 'TAF 25 mg/j'), (' 0.5 mg/j', '0.5 mg/j'), ('100 mg/j', '100 mg/j'), ('25 mg/j', '25 mg/j'), ('600 mg/j', '600 mg/j'), ('180 g/semaine', '180 g/semaine'), ('400 mg', '400 mg'), ('1 cp/j', '1 cp/j'), ('400 mg', '400 mg'), ('1 comprimé matin et soir', '1 comprimé matin et soir'), ('3 cp une fois par jour', '3 cp une fois par jour')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='medicament',
            name='nommedicament',
            field=models.CharField(choices=[('TDF', 'TDF '), ('TAF', 'TAF'), ('Entecavir', 'Entecavir'), ('Lamivudine', 'Lamivudine'), ('Adéfovir', 'Adéfovir'), ('Telbivudine', 'Telbivudine'), ('Interferon pegylé', 'Interferon pegylé'), ('Bulevirtide', 'Bulevirtide'), ('Vitamine E', 'Vitamine E'), ('EPO', 'EPO'), ('G CSF', 'G CSF'), ('Thrombopoietine', 'Thrombopoietine'), ('Vaccination VHA', 'Vaccination VHA'), ('Vaccination VHB', 'Vaccination VHB'), ('Interferon pégylé', 'Interferon pégylé'), ('Sofosbuvir', 'Sofosbuvir'), ('Velpatasvir Cp 100 mg', 'Velpatasvir Cp 100 mg'), ('Sofosbuvir 400 mg', 'Sofosbuvir 400 mg'), ('Ledipasvir Cp', 'Ledipasvir Cp'), ('Ledipasvir 90 mg ', ' Ledipasvir 90 mg'), ('Dasabuvir  Cp à 250 mg ', ' Dasabuvir  Cp à 250 mg'), ('Paritaprevir/ritonavir', 'Paritaprevir/ritonavir'), ('Elbasvir Cp avec Grazoprevir 100 mg et Elbasvir 50 mg ', 'Elbasvir Cp avec Grazoprevir 100 mg et Elbasvir 50 mg ')], max_length=150),
        ),
    ]
